---

- name: Ensure Gitlab Runner repository
  ansible.builtin.script:
    cmd: "{{ role_path }}/files/script.deb.sh"
    creates: /etc/apt/sources.list.d/runner_gitlab-runner.list

- name: Ensure apt cache update
  ansible.builtin.apt:
    update_cache: yes
  changed_when: false

- name: Ensure install Gitlab runner     
  ansible.builtin.apt:
    name:         gitlab-runner
  environment:
    GITLAB_RUNNER_DISABLE_SKEL: 'true'

- name: Ensure register gitlab-runner
  ansible.builtin.shell: 
    cmd: gitlab-runner register
        --non-interactive
        --name {{ gitlab_runner_name }}
        --url {{ gitlab_runner_gitlab_url }} 
        --executor {{ gitlab_runner_executor }}
        --docker-image {{ gitlab_runner_docker_image }}
        --docker-pull-policy {{ gitlab_runner_docker_pull_policy }}
        --token {{ gitlab_runner_token }}
        --locked="{{ gitlab_runner_locked }}"
        {{ (gitlab_runner_s3_cache_minio_args | join(' ')) if gitlab_runner_s3_cache_minio else '' }}
      && touch ansible-shell-done-gitlab-runner-register-{{ gitlab_runner_executor }}
      && rm -f ansible-shell-done-gitlab-runner-unregister-{{ gitlab_runner_executor }}
    creates: ansible-shell-done-gitlab-runner-register-{{ gitlab_runner_executor }}

- name: Ensure scheduled docker image prune -af
  ansible.builtin.cron:
    cron_file: "ansible_docker_image_prune_-af"
    user: root
    name: "ansible docker image prune -af"
    job: docker image prune -af
    hour: "{{ gitlab_runner_docker_prune_cron_hour }}"
    minute: "{{ gitlab_runner_docker_prune_cron_minute }}"
  when: gitlab_runner_docker_prune_cron

...