---

- name: Ensure GitLab runner install and register
  ansible.builtin.include_tasks: install_register.yml
  when: not gitlab_runner_unregister

- name: Ensure GitLab runner unregister
  ansible.builtin.include_tasks: unregister.yml
  when: gitlab_runner_unregister

...