---

- name: Ensure unregister gitlab-runner
  ansible.builtin.shell: gitlab-runner unregister
    --name "{{ gitlab_runner_description }}"
    && touch ansible-shell-done-gitlab-runner-unregister-{{ gitlab_runner_executor }}
    && rm -f ansible-shell-done-gitlab-runner-register-{{ gitlab_runner_executor }}
  args:
    creates: ansible-shell-done-gitlab-runner-unregister-{{ gitlab_runner_executor }}
    warn: false
  failed_when: False

- name: Ensure gitlab-runner docker container finished
  ansible.builtin.command: 
    cmd: docker ps --filter name=runner
  register: _result 
  until: _result.stdout.find("runner") == -1
  retries: 20
  delay: 20

...